[environments]
  [environments.development]
    name = "cloudtrail-elasticsearch"
    namespace = "elasticsearch"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
