# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 10
image:
  pullPolicy: IfNotPresent
  # repository: hiprabhat/cloudtrail-elasticsearch
  # tag: 8be92f6095eaa39988ca60d34f43d09fb1fe4eeb
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
